service: mcilroy
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2
functions:
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: get
    environment:
      S3_URL: https://mcilroy.s3-us-west-1.amazonaws.com
  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: get
    environment:
      S3_URL: https://mcilroy.s3-us-west-1.amazonaws.com
  profile:
    handler: handler.profile
    events:
      - http:
          path: profile
          method: get
