service: mcilroy
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2
functions:
  hello:
    handler: handler.login
    events:
      - http:
          path: login
          method: get
