service: mcilroy
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource: ${file(aws.yml):programs_arn}
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource:
        "Fn::GetAtt":
          - McIlroySessions
          - Arn
  environment:
    S3_URL: ${file(aws.yml):s3_url}
    STAGE: dev 
functions:
  saveProgram:
    handler: handler.saveProgram
    events:
      - http:
          path: programs/save
          method: POST
          authorizer:
            arn: ${file(aws.yml):userpool_arn}
  fetchPrograms:
    handler: handler.fetchPrograms
    events:
      - http:
          path: programs/fetch
          method: POST
          authorizer:
            arn: ${file(aws.yml):userpool_arn}
  deleteProgram:
    handler: handler.deleteProgram
    events:
      - http:
          path: programs/delete
          method: POST
          authorizer:
            arn: ${file(aws.yml):userpool_arn}
  sessions:
    handler: handler.sessions
    events:
      - http:
          path: sessions
          method: GET
      - http:
          path: sessions/{paths+}
          method: GET
      - http:
          path: sessions/api/{any+}
          method: POST

resources:
  Resources:
    McIlroySessions:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: McIlroySessions
        AttributeDefinitions:
          - 
            AttributeName: session
            AttributeType: S
        KeySchema:
          -
            AttributeName: session
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
