service: mcilroy
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource: ${file(aws.yml):programs_arn}
  environment:
    S3_URL: ${file(aws.yml):s3_url} 
functions:
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: get
  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: get
  profile:
    handler: handler.profile
    events:
      - http:
          path: profile
          method: get
  auth:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: post
          authorizer:
            arn: ${file(aws.yml):userpool_arn}
  api:
    handler: handler.api
    events:
      - http:
          path: api
          method: get
  app:
    handler: handler.app
    events:
      - http:
          path: app
          method: get
  saveProgram:
    handler: handler.saveProgram
    events:
      - http:
          path: programs/save
          method: POST
          authorizer:
            arn: ${file(aws.yml):userpool_arn}
  fetchPrograms:
    handler: handler.fetchPrograms
    events:
      - http:
          path: programs/fetch
          method: POST
          authorizer:
            arn: ${file(aws.yml):userpool_arn}

